# "Data Manipulation - d2l.ai Exercises - Part 1"
> "The first notebook in a series to be posted aiming to solve and understand exercises from d2l.ai curriculum on deep learning"
- toc: false
- branch: master
- badges: true
- comments: true
- categories: [d2l.ai-exercises, deep-learning, tensorflow]
- hide: false

This is the first notebook in a series to be posted aiming to solve and understand exercises from d2l.ai curriculum on deep learning, the corresponding lesson reference for this notebook is [this link](https://d2l.ai/chapter_preliminaries/ndarray.html).

This series of practice notebook posts may use the exercises and content provided from [d2l.ai](https://d2l.ai/), I write these to get a good hands-on practice in deep learning.

In [ ]:
import tensorflow as tf

In [ ]:
tf.__version__

'2.4.1'

## Setup for exercises

### Problem 1

In [ ]:
X = tf.reshape(tf.range(12, dtype=tf.float32), (3, 4))
Y = tf.constant([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
X, Y

(<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]], dtype=float32)>)

### Problem 2

In [ ]:
a = tf.reshape(tf.range(3), (3, 1))
b = tf.reshape(tf.range(2), (1, 2))
a, b

(<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
 array([[0],
        [1],
        [2]], dtype=int32)>,
 <tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[0, 1]], dtype=int32)>)

## Solutions

### Problem 1

In [ ]:
X == Y

<tf.Tensor: shape=(3, 4), dtype=bool, numpy=
array([[False,  True, False,  True],
       [False, False, False, False],
       [False, False, False, False]])>

In [ ]:
# Replacing == with comparison operators
X < Y

<tf.Tensor: shape=(3, 4), dtype=bool, numpy=
array([[ True, False,  True, False],
       [False, False, False, False],
       [False, False, False, False]])>

In [ ]:
# Replacing == with comparison operators
X > Y

<tf.Tensor: shape=(3, 4), dtype=bool, numpy=
array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])>

The operations are as expected of an elementwise comparison. Let's try to check if the operations are opposites of each other by trying to `not` one of them.

In [ ]:
(X > Y) == tf.math.logical_not(X < Y)

<tf.Tensor: shape=(3, 4), dtype=bool, numpy=
array([[ True, False,  True, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])>

We can see that apart from two cases where the numbers were equal(1 and 3), all the other values matched

### Problem 2

In [ ]:
# we need to change tensors a and b with 3-d tensors
a = tf.reshape(tf.range(16), (2, 4, -1))
b = tf.reshape(tf.range(16), (4, 2, -1))
a, b

(<tf.Tensor: shape=(2, 4, 2), dtype=int32, numpy=
 array([[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],
 
        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]], dtype=int32)>,
 <tf.Tensor: shape=(4, 2, 2), dtype=int32, numpy=
 array([[[ 0,  1],
         [ 2,  3]],
 
        [[ 4,  5],
         [ 6,  7]],
 
        [[ 8,  9],
         [10, 11]],
 
        [[12, 13],
         [14, 15]]], dtype=int32)>)

In [ ]:
a + b

InvalidArgumentError: ignored

I tried using tensors of 3d shapes, thinking it might but it did'nt, so I was searching about the rules to determine whether an array can be broadcasted or not and found this [documentation](https://numpy.org/doc/stable/user/basics.broadcasting.html), where the conditions are explained, the main points to consider broadcasting are, if the dimensions

- are equal, or

- one of them is 1

In the above case we hade shapes: `[2,4,2]` vs. `[4,2,2]`, Let's try a different shape

In [ ]:
a = tf.reshape(tf.range(12), (6, 2, -1))
b = tf.reshape(tf.range(16), (1, -1))
a, b

(<tf.Tensor: shape=(6, 2, 1), dtype=int32, numpy=
 array([[[ 0],
         [ 1]],
 
        [[ 2],
         [ 3]],
 
        [[ 4],
         [ 5]],
 
        [[ 6],
         [ 7]],
 
        [[ 8],
         [ 9]],
 
        [[10],
         [11]]], dtype=int32)>, <tf.Tensor: shape=(1, 16), dtype=int32, numpy=
 array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]],
       dtype=int32)>)

In [ ]:
a + b

<tf.Tensor: shape=(6, 2, 16), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]],

       [[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
        [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18]],

       [[ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]],

       [[ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
        [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]],

       [[ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]],

       [[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]]],
      dtype=int32)>

Similar to the examples in the [link](https://numpy.org/doc/stable/user/basics.broadcasting.html), the above example followed the rules and operation(addition) could happen with the help of broadcasting.
```python
    a - 6 X 2 X 1
    b -     1 X 16
a + b - 6 X 2 X 16
```     